# uncomment d4xx driver boot options corresponding to your Intel platform
#
# MTL GMSL2 AIC max9296 device generally on i2c-2 and i2c-3 buses
#options d4xx des_addr=0x48,0x4a,0x48,0x4a serdes_bus=2,2,3,3
# ARL GMSL2 AIC max9296 device generally on i2c-0 and i2c-3  buses
#options d4xx des_addr=0x48,0x4a,0x48,0x4a serdes_bus=0,0,3,3
# ADL/RPL/ASL GMSL2 AIC max9296 device generally on i2c-4 bus
#options d4xx des_addr=0x48,0x4a,0x68,0x6c serdes_bus=4,4,4,4
# ARL GMSL2 AIC dual-max96712 device generally on i2c-0 bus
#options d4xx des_addr=0x6b,0x6b,0x29,0x29 serdes_bus=0,0,0,0

# PTL GMSL2 AIC dual-max96724 device generally on i2c-0 and i2c-1 buses
options d4xx des_addr=0x27,0x27,0x27,0x27 serdes_bus=0,0,1,1 des_csi=0,0,2,2
# !!WARNING!! Intel Servoss Mountain 1.0 (Fab A) dual-max96724 board cphy CRD connectivity is inverted
# max96724 csi 0 CPHY-2T DA0/DA1 maps to ipu7 isys csi 2
# max96724 csi 2 CPHY-2T DB0/DB1 maps to ipu7 isys csi 0
#options d4xx des_addr=0x27,0x27,0x27,0x27 serdes_bus=1,1,2,2 des_csi=2,2,0,0
#

#options d4xx dyndbg
#options d4xx-max9295 dyndbg
#options d4xx-max9296 dyndbg
#options d4xx-max96724 dyndbg
