#!/bin/bash
# file: rs_ipu7_d457_bind.sh
# This script used for binding media links of v4l2 subdevice entities
# The configuration we had is DS5 mux and IPU7 entities.
# _______  _______  _______  _________
# |depth|->| mux |->|CSI-2|->|capture|
# |_____|  |_____|  |_____|  |_______|
#
# Full graph can be viewed on http://magjac.com/graphviz-visual-editor/
# media graph links can be generated by running 'media-ctl --print-dot'
#
# Dependency: v4l-utils
v4l2_util=$(which v4l2-ctl)
media_util=$(which media-ctl)
if [ -z ${v4l2_util} ]; then
  echo "v4l2-ctl not found, install with: sudo apt install v4l-utils"
  exit 1
fi
# enable metadata capture nodes for default
metadata_enabled=1
while [[ $# -gt 0 ]]; do
  case $1 in
    -q|--quiet)
      quiet=1
      shift
    ;;
    -m|--mux)
      shift
      if [ ${#1} -eq 3 ]; then
	 mux_param=$1
      fi
      shift
    ;;
    -n|--no-metadata)
      metadata_enabled=0
      shift
    ;;
    -h|--help)
      echo "-q -m -n -h"
    ;;
    *)
      quiet=0
      shift
    ;;
    esac
done

# mapping for DS5 mux entity to IPU6 CSI-2 entity matching.
declare -A media_mux_capture_link=( [0]=0 [1]=16 [2]=32)

# all available DS5 muxes, each one represent physically connected camera.
# muxes prefix a, b, c, d referes to max96724 aggregated link cameras
# muxes suffix 0, 1, 2, 3, 4, 5 is referes to csi2 mipi port mapping

mux_list=${mux_param:-'a-0 b-0 c-0 d-0 a-1 b-1 c-1 d-1 a-2 b-2 c-2 d-2 a-3 b-3 c-3 d-3 a-4 b-4 c-4 d-4 a-5 b-5 c-5 d-5'}

# vc_id mapping for D4XX sensor entity to IPU6|IPU7 CSI-2 pad.
# IPU7 CSI-2 pad  1, vc 0, depth a-?
# IPU7 CSI-2 pad  2, vc 4, depth c-? or meta data a-?
# IPU7 CSI-2 pad  3, vc 1, RGB a-?
# IPU7 CSI-2 pad  4, vc 5, RGB c-? or meta data a-?
# IPU7 CSI-2 pad  5, vc 6, IR a-?
# IPU7 CSI-2 pad  6, vc 7, IMU a-?
# Aggregated-links
# IPU7 CSI-2 pad  7, vc 2,  depth b-?
# IPU7 CSI-2 pad  8, vc 6,  depth d-? or meta data b-?
# IPU7 CSI-2 pad  9, vc 3,  RGB b-?
# IPU7 CSI-2 pad  10, vc 7,  RGB d-? or meta data b-?
# IPU7 CSI-2 pad  11, vc 4, IR b-?
# IPU7 CSI-2 pad  12, vc 5, IMU b-?
# IPU7 CSI-2 pad  13, vc 2, IR c-?
# IPU7 CSI-2 pad  14, vc 3, IMU c-?
# IPU7 CSI-2 pad  15, vc 0, IR d-?
# IPU7 CSI-2 pad  16, vc 1, IMU d-?
#declare -A media_sensor_csi_route=( [1]=0 [2]=4 [3]=1 [4]=5 [5]=6 [6]=7 [7]=2 [8]=6 [9]=3 [10]=7 [11]=4 [12]=5 [13]=2 [14]=3 [15]=0 [16]=1 )

# vc_id mapping for D4XX sensor entity to IPU6|IPU7 CSI-2 pad.
# IPU7 CSI-2 pad  1, vc 0, depth a-?
# IPU7 CSI-2 pad  2, vc 1, depth c-? or meta data a-?
# IPU7 CSI-2 pad  3, vc 1, RGB a-?
# IPU7 CSI-2 pad  4, vc 0, RGB c-? or meta data a-?
# IPU7 CSI-2 pad  5, vc 2, IR a-?
# IPU7 CSI-2 pad  6, vc 3, IMU a-?
# Aggregated-links
# ipu7 CSI-2 pad  7, vc 2,  depth b-?
# IPU7 CSI-2 pad  8, vc 3,  depth d-? or meta data b-?
# IPU7 CSI-2 pad  9, vc 3,  RGB b-?
# IPU7 CSI-2 pad  10, vc 2,  RGB d-? or meta data b-?
# IPU7 CSI-2 pad  11, vc 0, IR b-?
# IPU7 CSI-2 pad  12, vc 1, IMU b-?
# IPU7 CSI-2 pad  13, vc 2, IR c-?
# IPU7 CSI-2 pad  14, vc 3, IMU c-?
# IPU7 CSI-2 pad  15, vc 1, IR d-?
# IPU7 CSI-2 pad  16, vc 0, IMU d-?
declare -A media_sensor_csi_route=( [1]=0 [2]=1 [3]=1 [4]=0 [5]=2 [6]=3 [7]=2 [8]=3 [9]=3 [10]=2 [11]=0 [12]=1 [13]=2 [14]=3 [15]=1 [16]=0 )

# Find media device.
# For case with usb camera plugged in during the boot,
# usb media controller will occupy index 0
mdev=$(${v4l2_util} --list-devices | grep -A100 ipu | grep media)
[[ -z "${mdev}" ]] && exit 0

# Find IPU PCI device gen name
cap_prefix=$(${v4l2_util} --list-devices | grep ipu | grep PCI | sed 's/^\(ipu[6|7]\).*/\1/' | tr '[:lower:]' '[:upper:]')
[[ -z "${cap_prefix}" ]] && exit 0

media_ctl_cmd="${media_util} -d ${mdev}"
out $media_ctl_cmd -r # <- this can be used to clean-up all bindings from media controller
# cache media-ctl output
dot=$($media_ctl_cmd --print-dot)

fmt_depth="${fmt:-[fmt:UYVY8_1X16/640x480 field:none]}"
fmt_rgb="${fmt:-[fmt:YUYV8_1X16/640x480 field:none]}"
fmt_ir="${fmt:-[fmt:VYUY8_1X16/640x480 field:none]}"
# For fimware version starting from: 5.16,
# IMU will have 32bit axis values.
# 5.16.x.y = firmware version: 0x0510
# state->fw_version < 0x510
fmt_imu="${fmt:-[fmt:Y8_1X8/32x1 field:none]}"
# state->fw_version >= 0x510
#fmt_imu="${fmt:-[fmt:Y8_1X8/38x1 field:none]}"
out() {
  [[ $quiet -eq 0 ]] && echo -n "${@}    " >&2
  "${@}"
  [[ $quiet -eq 0 ]] && echo "        RET=$?" >&2
}

# DS5 MUX. Can be max9296 or max96724 aggregated {a, b, c, d} accross mipi port {0, 1, 2, 3, 4, 5}.
for camera in ${mux_list}; do
    
  is_mux=$(echo "${dot}" | grep "DS5 mux ${camera}")
  # skip for non-existing muxes
  [[ -z $is_mux ]] && continue;
  
  [[ $quiet -eq 0 ]] && echo -n "Bind $cap_prefix to DS5 mux ${camera} .. "

  csi2="$((${camera:2:1}))"
  mux=${camera:0:1}

  # mapping for DS5 mux entity to IPU7 ISYS entity matching.
  # for DS5 aggregated mux (above a) - use ISYS capture pads with offset 6
  # this offset used as capture sensor set - dept,rgb,ir,imu = 4
  cap_pad="$((${media_mux_capture_link[${csi2}]}))"
  isys_pad=0
  if [ "${mux}" \= "b" ]; then
    isys_pad=6
  else
      if  [ "${mux}" \= "c" ]; then
	   metadata_enabled=0
	   isys_pad=1
      else
	  if  [ "${mux}" \= "d" ]; then
		metadata_enabled=0
		isys_pad=7
	    fi
       fi
  fi
  cap_pad=$((${cap_pad}+${isys_pad}))

  # DEPTH video streaming node (no metadata)
  out $media_ctl_cmd -v -l "\"Intel ${cap_prefix} CSI2 ${csi2}\":$((${isys_pad}+1)) -> \"Intel ${cap_prefix} ISYS Capture $((${cap_pad}+0))\":0[1]" 1>/dev/null
  # DEPTH metadata node
  if [[ $metadata_enabled -eq 1 ]]; then
     out $media_ctl_cmd -v -l "\"Intel ${cap_prefix} CSI2 ${csi2}\":$((${isys_pad}+2)) -> \"Intel ${cap_prefix} ISYS Capture $((${cap_pad}+1))\":0[1]" 1>/dev/null
  fi

  # RGB link video streaming node (no metadata)
  out $media_ctl_cmd -v -l "\"Intel ${cap_prefix} CSI2 ${csi2}\":$((${isys_pad}+3)) -> \"Intel ${cap_prefix} ISYS Capture $((${cap_pad}+2))\":0[1]" 1>/dev/null
  # RGB metadata node
  if [[ $metadata_enabled -eq 1 ]]; then
      out $media_ctl_cmd -v -l "\"Intel ${cap_prefix} CSI2 ${csi2}\":$((${cap_pad}+4)) -> \"Intel ${cap_prefix} ISYS Capture $((${cap_pad}+3))\":0[1]" 1>/dev/null
  fi

  cap_pad_depth=$((${cap_pad}+0))
  cap_pad_rgb=$((${cap_pad}+2))
  isys_pad_depth=$((${isys_pad}+1))
  isys_pad_rgb=$((${isys_pad}+3))
  isys_vc_depth=$((${media_sensor_csi_route[${isys_pad_depth}]}+0))
  isys_vc_rgb=$((${media_sensor_csi_route[${isys_pad_rgb}]}+0))
  
  if [ "${mux}" \= "c" ]; then
      # remap IR amd IMU suffix c to CSI2 input 13 and 14
      isys_pad=$((${isys_pad}+7))
      cap_pad=$((${cap_pad}+7))
  else
      if  [ "${mux}" \= "d" ]; then
	  # remap IR amd IMU suffix d to CSI2 input 15 and 16
	  isys_pad=$((${isys_pad}+3))
	  cap_pad=$((${cap_pad}+3))
      fi
  fi
  # IR link video streaming node
  out $media_ctl_cmd -v -l "\"Intel ${cap_prefix} CSI2 ${csi2}\":$((${isys_pad}+5)) -> \"Intel ${cap_prefix} ISYS Capture $((${cap_pad}+4))\":0[1]" 1>/dev/null
  # IMU link streaming node
  out $media_ctl_cmd -v -l "\"Intel ${cap_prefix} CSI2 ${csi2}\":$((${isys_pad}+6)) -> \"Intel ${cap_prefix} ISYS Capture $((${cap_pad}+5))\":0[1]" 1>/dev/null

  cap_pad_ir=$((${cap_pad}+4))
  cap_pad_imu=$((${cap_pad}+5))
  isys_pad_ir=$((${isys_pad}+5))
  isys_pad_imu=$((${isys_pad}+6))
  isys_vc_ir=$((${media_sensor_csi_route[${isys_pad_ir}]}+0))
  isys_vc_imu=$((${media_sensor_csi_route[${isys_pad_imu}]}+0))

  # bind (enable) link DS5 mux pad 0 to CSI-2 pad 0
  out $media_ctl_cmd -v -l "\"DS5 mux ${mux}\":0 -> \"Intel ${cap_prefix} CSI-2 ${csi2}\":0[1]" 1>/dev/null

  # subdev entity '['pad-number '/' stream-number '->' pad-number '/' stream-number '[' route-flags ']' ']' ;
  # example:  /usr/bin/media-ctl -d /dev/media0 -R "'Intel ${cap_prefix} CSI2 2'[0/1->3/1,0/0->1/0]"
  # Set DEPTH+RGB+IR+IMU vc_id routes
  out $media_ctl_cmd -R "\"DS5 mux ${camera}\"[1/${isys_vc_depth}->0/${isys_vc_depth}[1], 2/${isys_vc_rgb}->0/${isys_vc_rgb}[1], 3/${isys_vc_ir}->0/${isys_vc_ir}[1], 4/${isys_vc_imu}->0/${isys_vc_imu}[1]]"
  if [[ $metadata_enabled -eq 1 ]]; then
      # Set DEPTH+DEPTH-md+RGB+RGB-md+IR+IMU vc_id routes
      out $media_ctl_cmd -R "\"Intel ${cap_prefix} CSI2 ${csi2}\"[0/${isys_vc_depth}->${isys_pad_depth}/${isys_vc_depth}[1], 0/${isys_vc_depth}->$((${isys_pad_depth}+1))/${isys_vc_depth}[1], 0/${isys_vc_rgb}->${isys_pad_rgb}/${isys_vc_rgb}[1], 0/${isys_vc_rgb}->$((${isys_pad_rgb}+1))/${isys_vc_rgb}[1], 0/${isys_vc_ir}->${isys_pad_ir}/${isys_vc_ir}[1], 0/${isys_vc_imu}->${isys_pad_imu}/${isys_vc_imu}[1]]"
  else
      # Set DEPTH+RGB+IR+IMU vc_id routes
      out $media_ctl_cmd -R "\"Intel ${cap_prefix} CSI2 ${csi2}\"[0/${isys_vc_depth}->${isys_pad_depth}/${isys_vc_depth}[1], 0/${isys_vc_rgb}->${isys_pad_rgb}/${isys_vc_rgb}[1], 0/${isys_vc_ir}->${isys_pad_ir}/${isys_vc_ir}[1], 0/${isys_vc_imu}->${isys_pad_imu}/${isys_vc_imu}[1]]"
  fi

  # DEPTH default media bus format
  out $media_ctl_cmd -V "\"Intel ${cap_prefix} CSI2 ${csi2}\":${isys_pad_depth}/${isys_vc_depth} ${fmt_depth}"
  out $media_ctl_cmd -V "\"DS5 mux ${camera}\":0/${isys_vc_depth} ${fmt_depth}"
  #out $media_ctl_cmd -V "\"DS5 mux ${camera}\":1/${isys_vc_depth} ${fmt_depth}"
  out $media_ctl_cmd -V "\"D4XX depth ${camera}\":0/${isys_vc_depth} ${fmt_depth}"
  # RGB default media bus format
  out $media_ctl_cmd -V "\"Intel ${cap_prefix} CSI2 ${csi2}\":${isys_pad_rgb}/${isys_vc_rgb} ${fmt_rgb}"
  out $media_ctl_cmd -V "\"DS5 mux ${camera}\":0/${isys_vc_rgb} ${fmt_rgb}"
  #out $media_ctl_cmd -V "\"DS5 mux ${camera}\":2/${isys_vc_rgb} ${fmt_rgb}"
  out $media_ctl_cmd -V "\"D4XX rgb ${camera}\":0/${isys_vc_rgb} ${fmt_rgb}"
  # IR default media bus format
  out $media_ctl_cmd -V "\"Intel ${cap_prefix} CSI2 ${csi2}\":${isys_pad_ir}/${isys_vc_ir} ${fmt_ir}"
  out $media_ctl_cmd -V "\"DS5 mux ${camera}\":0/${isys_vc_ir} ${fmt_ir}"
  #out $media_ctl_cmd -V "\"DS5 mux ${camera}\":3/${isys_vc_ir} ${fmt_ir}"
  out $media_ctl_cmd -V "\"D4XX ir ${camera}\":0/${isys_vc_ir} ${fmt_ir}"
  # IMU default media bus format
  out $media_ctl_cmd -V "\"Intel ${cap_prefix} CSI2 ${csi2}\":${isys_pad_imu}/${isys_vc_imu} ${fmt_imu}"
  out $media_ctl_cmd -V "\"DS5 mux ${camera}\":0/${isys_vc_imu} ${fmt_imu}"
  #out $media_ctl_cmd -V "\"DS5 mux ${camera}\":4/${isys_vc_imu} ${fmt_imu}"
  out $media_ctl_cmd -V "\"D4XX imu ${camera}\":0/${isys_vc_imu} ${fmt_imu}"

done
